create table TBL (ID NUMBER(1000));

INSERT INTO TBL (ID) VALUES (999);
DELETE FROM TBL WHERE ID = 999;
SELECT * FROM TBL

SELECT ID FROM TBL
GROUP BY ID
HAVING COUNT(*) = 2
ORDER BY (CASE WHEN ID = 999 THEN 0 ELSE ID END) ASC ;